stages:
  - deploy
  - production
cache:
 paths:
    - node_modules
deploy:
   image: docker:dind
   stage: deploy
   script:
     - docker build -t app/blog .
     - docker run -d -p 3000:3000 --rm --name newtest app/blog
   tags:
     - docker
   only:
     - master
production:
   stage: production
   script:
     - git config git-ftp.url "ftp://zaiter.its.ae:21/public_html/next"
     - git config git-ftp.user "zaiterits"
     - git config git-ftp.password "password"
     - ls
# Upload all files
    
   # - git ftp init

# Or if the files are already there
     - git ftp catchup

# Work and deploy 
     - echo "new content" >> index.txt
   # - git commit index.txt -m "Add new content"
     - git ftp push
     - lftp -e "set ssl:check-hostname no; mirror -vvv -R . ./public_html/next --parallel=20 --exclude-glob .git* --exclude .git/ ; quit" -u zaiterits,password zaiter.its.ae
    

   tags:
     - docker
   only:
     - master
